version: '3'
services:
  concourse-db:
    image: postgres:11.2
    volumes:
      - concourse-db:/database
    environment:
      POSTGRES_USER:     concourse_postgres_user
      POSTGRES_PASSWORD: concourse_postgres_pass
      POSTGRES_DB:       concourse
      PGDATA:            /database

  concourse-web:
    image: concourse/concourse:5.1.0
    command: web
    privileged: true
    depends_on:
      - concourse-db
      - minio
    ports:
      - 8080:8080
      - 2222:2222
    volumes:
      - ./concourse-keys/host:/concourse-keys
    environment:
      CONCOURSE_POSTGRES_HOST:        concourse-db
      CONCOURSE_POSTGRES_USER:        concourse_postgres_user
      CONCOURSE_POSTGRES_PASSWORD:    concourse_postgres_pass
      CONCOURSE_POSTGRES_DATABASE:    concourse
      CONCOURSE_EXTERNAL_URL:         http://127.0.0.1:8080
      CONCOURSE_ADD_LOCAL_USER:       admin:admin,user1:user1,guest:guest
      CONCOURSE_MAIN_TEAM_LOCAL_USER: admin

  concourse-worker:
    image: concourse/concourse:5.1.0
    command: worker
    privileged: true
    depends_on:
      - concourse-web
    volumes:
      - ./concourse-keys/worker:/concourse-keys
    environment:
      CONCOURSE_TSA_HOST: concourse-web:2222

  minio:
    image: minio/minio:latest
    command: server /data
    volumes:
      - ./minio-data:/data
    ports:
      - 9000:9000
    environment:
      MINIO_REGION: ap-northeast-1
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key

volumes:
  concourse-db:
    driver: local
