version: '3'
services:
  concourse-db:
    image: postgres:11.2
    volumes:
      - concourse-db:/database
    environment:
      POSTGRES_USER:     concourse_postgres_user
      POSTGRES_PASSWORD: concourse_postgres_pass
      POSTGRES_DB:       concourse
      PGDATA:            /database

  concourse-web:
    image: concourse/concourse:5.0.1
    command: web
    privileged: true
    depends_on:
      - concourse-db
    ports:
      - 8080:8080
      - 2222:2222
    volumes:
      - ./concourse-keys/host:/concourse-keys
    environment:
      CONCOURSE_POSTGRES_HOST:        concourse-db
      CONCOURSE_POSTGRES_USER:        concourse_postgres_user
      CONCOURSE_POSTGRES_PASSWORD:    concourse_postgres_pass
      CONCOURSE_POSTGRES_DATABASE:    concourse
      CONCOURSE_EXTERNAL_URL:         http://127.0.0.1:8080
      CONCOURSE_ADD_LOCAL_USER:       admin:admin
      CONCOURSE_MAIN_TEAM_LOCAL_USER: admin

  concourse-worker:
    image: concourse/concourse:5.0.1
    command: worker
    privileged: true
    links:
      - concourse-web
    depends_on:
      - concourse-web
    volumes:
      - ./concourse-keys/worker:/concourse-keys
    environment:
      CONCOURSE_TSA_HOST: concourse-web:2222

volumes:
  concourse-db:
    driver: local
