resources:
  - name: 10m
    type: time
    source: { interval: 10m }

jobs:
  - name: periodic
    plan:
      - get: 10m
        trigger: true
      - task: periodic-task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: busybox }
          run:
            path: echo
            args:
              - triggered!
